// Code generated by "stringer -type=Type"; DO NOT EDIT.

package social

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Facebook-0]
	_ = x[Instagram-1]
	_ = x[Github-2]
	_ = x[Twitch-3]
	_ = x[LinkedIn-4]
	_ = x[Youtube-5]
	_ = x[Dribble-6]
}

const _Type_name = "FacebookInstagramGithubTwitchLinkedInYoutubeDribble"

var _Type_index = [...]uint8{0, 8, 17, 23, 29, 37, 44, 51}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
